export const ciudadesNacimiento = [
  // ANTIOQUIA
  'MEDELLIN - ANTIOQUIA',
  'CALDAS - ANTIOQUIA',
  'ENVIGADO - ANTIOQUIA',
  'HISPANIA - ANTIOQUIA',
  'BELLO - ANTIOQUIA',
  'SABANETA - ANTIOQUIA',
  'ITAGUI - ANTIOQUIA',
  'RIONEGRO - ANTIOQUIA',
  'APARTADO - ANTIOQUIA', // Nueva ciudad añadida

  // ATLANTICO
  'BARRANQUILLA - ATLANTICO',
  'SOLEDAD - ATLANTICO',
  'MALAMBO - ATLANTICO', // Nueva ciudad añadida

  // BOLIVAR
  'CARTAGENA - BOLIVAR',
  'MAGANGUE - BOLIVAR',
  'TURBACO - BOLIVAR', // Nueva ciudad añadida

  // BOYACA
  'TUNJA - BOYACA',
  'DUITAMA - BOYACA',
  'SOGAMOSO - BOYACA', // Nueva ciudad añadida

  // CALDAS
  'MANIZALES - CALDAS',
  'CHINCHINA - CALDAS',

  // CASANARE
  'YOPAL - CASANARE',
  'AGUAZUL - CASANARE',

  // CAUCA
  'POPAYAN - CAUCA',
  'SANTANDER DE QUILICHAO - CAUCA',

  // CESAR
  'VALLEDUPAR - CESAR',
  'AGUACHICA - CESAR',

  // CORDOBA
  'MONTERIA - CORDOBA',
  'LORICA - CORDOBA',
  'SAHAGUN - CORDOBA',

  // CUNDINAMARCA
  'BOGOTA D.C - CUNDINAMARCA',
  'BOGOTA D.C - ANTONIO NARIÑO',
  'CHIA - CUNDINAMARCA',
  'ZIPAQUIRA - CUNDINAMARCA',
  'FACATATIVA - CUNDINAMARCA',
  'SOACHA - CUNDINAMARCA',
  'FUSAGASUGA - CUNDINAMARCA', // Nueva ciudad añadida

  // HUILA
  'NEIVA - HUILA',
  'LA PLATA - HUILA',
  'PITALITO - HUILA',
  'GARZON - HUILA',
  'CAMPOALEGRE - HUILA',
  'RIVERA - HUILA',

  // MAGDALENA
  'SANTA MARTA - MAGDALENA',
  'CIENAGA - MAGDALENA',

  // META
  'VILLAVICENCIO - META',
  'ACACIAS - META',
  'GRANADA - META', // Nueva ciudad añadida

  // NARIÑO
  'PASTO - NARIÑO',
  'IPIALES - NARIÑO',
  'TUMACO - NARIÑO', // Nueva ciudad añadida

  // NORTE DE SANTANDER
  'CUCUTA - NORTE DE SANTANDER',
  'OCAÑA - NORTE DE SANTANDER',
  'PAMPLONA - NORTE DE SANTANDER', // Nueva ciudad añadida

  // QUINDIO
  'ARMENIA - QUINDIO',
  'CALARCA - QUINDIO', // Nueva ciudad añadida

  // RISARALDA
  'PEREIRA - RISARALDA',
  'DOSQUEBRADAS - RISARALDA',
  'SANTA ROSA DE CABAL - RISARALDA', // Nueva ciudad añadida

  // SANTANDER
  'BUCARAMANGA - SANTANDER',
  'FLORIDABLANCA - SANTANDER',
  'GIRON - SANTANDER',
  'BARRANCABERMEJA - SANTANDER',
  'PIEDECUESTA - SANTANDER',
  'MALAGA - SANTANDER',

  // SUCRE
  'SINCELEJO - SUCRE',
  'COROZAL - SUCRE',

  // TOLIMA
  'IBAGUE - TOLIMA',
  'ESPINAL - TOLIMA',
  'MELGAR - TOLIMA', // Nueva ciudad añadida

  // VALLE DEL CAUCA
  'CALI - VALLE DEL CAUCA',
  'CARTAGO - VALLE DEL CAUCA',
  'LA UNION - VALLE DEL CAUCA',
  'BUENAVENTURA - VALLE DEL CAUCA',
  'PALMIRA - VALLE DEL CAUCA',
  'TULUA - VALLE DEL CAUCA',
  'YUMBO - VALLE DEL CAUCA', // Nueva ciudad añadida
  
  // NUEVOS DEPARTAMENTOS
  'SAN JOSE DEL GUAVIARE - GUAVIARE', // Ciudad solicitada
  'LETICIA - AMAZONAS', // Nueva ciudad añadida
  'ARAUCA - ARAUCA', // Nueva ciudad añadida
  'QUIBDO - CHOCO', // Nueva ciudad añadida
  'RIOHACHA - LA GUAJIRA', // Nueva ciudad añadida
  'MOCOA - PUTUMAYO' // Nueva ciudad añadida
];