export const ciudadesNacimiento = [
  // ANTIOQUIA
  'MEDELLIN - ANTIOQUIA',
  'CALDAS - ANTIOQUIA',
  'ENVIGADO - ANTIOQUIA',
  'HISPANIA - ANTIOQUIA',
  'BELLO - ANTIOQUIA',
  'SABANETA - ANTIOQUIA',
  'ITAGUI - ANTIOQUIA',
  'RIONEGRO - ANTIOQUIA', // Nueva ciudad añadida

  // ATLANTICO
  'BARRANQUILLA - ATLANTICO',
  'SOLEDAD - ATLANTICO',

  // BOLIVAR
  'CARTAGENA - BOLIVAR',
  'MAGANGUE - BOLIVAR',

  // BOYACA
  'TUNJA - BOYACA', // Ya estaba en la lista
  'DUITAMA - BOYACA',

  // CALDAS
  'MANIZALES - CALDAS',
  'CHINCHINA - CALDAS',

  // CASANARE
  'YOPAL - CASANARE',
  'AGUAZUL - CASANARE',

  // CAUCA
  'POPAYAN - CAUCA',
  'SANTANDER DE QUILICHAO - CAUCA',

  // CESAR
  'VALLEDUPAR - CESAR',
  'AGUACHICA - CESAR',

  // CORDOBA
  'MONTERIA - CORDOBA', // Nueva ciudad añadida
  'LORICA - CORDOBA', // Nueva ciudad añadida
  'SAHAGUN - CORDOBA', // Nueva ciudad añadida

  // CUNDINAMARCA
  'BOGOTA D.C - CUNDINAMARCA',
  'BOGOTA D.C - ANTONIO NARIÑO',
  'CHIA - CUNDINAMARCA',
  'ZIPAQUIRA - CUNDINAMARCA',
  'FACATATIVA - CUNDINAMARCA', // Nueva ciudad añadida
  'SOACHA - CUNDINAMARCA', // Nueva ciudad añadida

  // HUILA
  'NEIVA - HUILA',
  'LA PLATA - HUILA',
  'PITALITO - HUILA',
  'GARZON - HUILA',
  'CAMPOALEGRE - HUILA',
  'RIVERA - HUILA',

  // MAGDALENA
  'SANTA MARTA - MAGDALENA',
  'CIENAGA - MAGDALENA',

  // META
  'VILLAVICENCIO - META',
  'ACACIAS - META',

  // NARIÑO
  'PASTO - NARIÑO',
  'IPIALES - NARIÑO',

  // NORTE DE SANTANDER
  'CUCUTA - NORTE DE SANTANDER',
  'OCAÑA - NORTE DE SANTANDER',

  // QUINDIO
  'ARMENIA - QUINDIO', // Nueva ciudad añadida

  // RISARALDA
  'PEREIRA - RISARALDA',
  'DOSQUEBRADAS - RISARALDA',

  // SANTANDER
  'BUCARAMANGA - SANTANDER',
  'FLORIDABLANCA - SANTANDER',
  'GIRON - SANTANDER',
  'BARRANCABERMEJA - SANTANDER', // Nueva ciudad añadida
  'PIEDECUESTA - SANTANDER', // Nueva ciudad añadida
  'MALAGA - SANTANDER', // Nueva ciudad añadida

  // SUCRE
  'SINCELEJO - SUCRE',
  'COROZAL - SUCRE',

  // TOLIMA
  'IBAGUE - TOLIMA',
  'ESPINAL - TOLIMA',

  // VALLE DEL CAUCA
  'CALI - VALLE DEL CAUCA',
  'CARTAGO - VALLE DEL CAUCA',
  'LA UNION - VALLE DEL CAUCA',
  'BUENAVENTURA - VALLE DEL CAUCA',
  'PALMIRA - VALLE DEL CAUCA', // Nueva ciudad añadida
  'TULUA - VALLE DEL CAUCA' // Nueva ciudad añadida
];